namespace PmviewHostProjector.Scaffolding;

/// <summary>
/// Scaffolds a complete Godot .NET project: project.godot, .csproj, .sln,
/// and main.tscn with camera/lighting. Idempotent — safe to re-run.
/// </summary>
public static class ProjectScaffolder
{
    public static void Scaffold(string projectDir)
    {
        Directory.CreateDirectory(projectDir);
        var projectName = SanitiseProjectName(Path.GetFileName(Path.GetFullPath(projectDir)));

        WriteProjectGodotIfMissing(projectDir, projectName);
        WriteCsprojIfMissing(projectDir, projectName);
        WriteSlnIfMissing(projectDir, projectName);
        WriteMainScene(projectDir);
    }

    private static void WriteProjectGodotIfMissing(string dir, string name)
    {
        var path = Path.Combine(dir, "project.godot");
        if (File.Exists(path)) return;

        var content =
            "; Engine configuration file (generated by pmview-host-projector)\n" +
            "\n" +
            "[application]\n" +
            "\n" +
            $"config/name=\"{name}\"\n" +
            "config/description=\"PCP performance metrics as living 3D environments\"\n" +
            "run/main_scene=\"res://scenes/main.tscn\"\n" +
            "config/features=PackedStringArray(\"4.6\", \"C#\", \"Forward Plus\")\n" +
            "\n" +
            "[dotnet]\n" +
            "\n" +
            $"project/assembly_name=\"{name}\"\n";
        File.WriteAllText(path, content);
    }

    private static void WriteCsprojIfMissing(string dir, string name)
    {
        if (Directory.GetFiles(dir, "*.csproj").Length > 0) return;

        var content =
            "<Project Sdk=\"Godot.NET.Sdk/4.6.1\">\n" +
            "  <PropertyGroup>\n" +
            "    <TargetFramework>net8.0</TargetFramework>\n" +
            "    <EnableDynamicLoading>true</EnableDynamicLoading>\n" +
            "    <Nullable>enable</Nullable>\n" +
            "  </PropertyGroup>\n" +
            "</Project>\n";
        File.WriteAllText(Path.Combine(dir, $"{name}.csproj"), content);
    }

    private static void WriteSlnIfMissing(string dir, string name)
    {
        if (Directory.GetFiles(dir, "*.sln").Length > 0) return;

        var guid = Guid.NewGuid().ToString("D").ToUpperInvariant();
        var content =
            "Microsoft Visual Studio Solution File, Format Version 12.00\n" +
            $"Project(\"{{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}}\") = \"{name}\", \"{name}.csproj\", \"{{{guid}}}\"\n" +
            "EndProject\n" +
            "Global\n" +
            "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n" +
            "\t\tDebug|Any CPU = Debug|Any CPU\n" +
            "\t\tRelease|Any CPU = Release|Any CPU\n" +
            "\tEndGlobalSection\n" +
            "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n" +
            $"\t\t{{{guid}}}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\n" +
            $"\t\t{{{guid}}}.Debug|Any CPU.Build.0 = Debug|Any CPU\n" +
            $"\t\t{{{guid}}}.Release|Any CPU.ActiveCfg = Release|Any CPU\n" +
            $"\t\t{{{guid}}}.Release|Any CPU.Build.0 = Release|Any CPU\n" +
            "\tEndGlobalSection\n" +
            "EndGlobal\n";
        File.WriteAllText(Path.Combine(dir, $"{name}.sln"), content);
    }

    private static void WriteMainScene(string dir)
    {
        var scenesDir = Path.Combine(dir, "scenes");
        Directory.CreateDirectory(scenesDir);
        File.WriteAllText(Path.Combine(scenesDir, "main.tscn"), MainSceneWriter.Write());
    }

    private static string SanitiseProjectName(string dirName) =>
        string.IsNullOrWhiteSpace(dirName) ? "pmview-project" : dirName;
}
