using System.Collections.Generic;

namespace PmviewHostProjector.Scaffolding;

/// <summary>
/// Scaffolds a complete Godot .NET project: project.godot, .csproj, .sln,
/// and main.tscn with camera/lighting. Idempotent — safe to re-run.
/// Use force to overwrite existing files.
/// </summary>
public static class ProjectScaffolder
{
    public static ScaffoldResult Scaffold(string projectDir, bool force = false)
    {
        Directory.CreateDirectory(projectDir);
        var projectName = SanitiseProjectName(Path.GetFileName(Path.GetFullPath(projectDir)));
        var result = new ScaffoldResult();

        WriteProjectGodot(projectDir, projectName, force, result);
        WriteCsproj(projectDir, projectName, force, result);
        WriteSln(projectDir, projectName, force, result);
        WriteMainScene(projectDir, force, result);

        return result;
    }

    private static void WriteProjectGodot(string dir, string name, bool force, ScaffoldResult result)
    {
        var path = Path.Combine(dir, "project.godot");
        if (File.Exists(path) && !force)
        {
            result.Skipped.Add("project.godot");
            return;
        }

        var existed = File.Exists(path);
        var content =
            "; Engine configuration file (generated by pmview-host-projector)\n" +
            "\n" +
            "[application]\n" +
            "\n" +
            $"config/name=\"{name}\"\n" +
            "config/description=\"PCP performance metrics as living 3D environments\"\n" +
            "run/main_scene=\"res://scenes/main.tscn\"\n" +
            "config/features=PackedStringArray(\"4.6\", \"C#\", \"Forward Plus\")\n" +
            "\n" +
            "[display]\n" +
            "\n" +
            "window/size/viewport_width=1920\n" +
            "window/size/viewport_height=1080\n" +
            "window/stretch/mode=\"viewport\"\n" +
            "\n" +
            "[dotnet]\n" +
            "\n" +
            $"project/assembly_name=\"{name}\"\n";
        File.WriteAllText(path, content);
        (existed ? result.Overwritten : result.Created).Add("project.godot");
    }

    private static void WriteCsproj(string dir, string name, bool force, ScaffoldResult result)
    {
        var existing = Directory.GetFiles(dir, "*.csproj");
        var relativeName = $"{name}.csproj";

        if (existing.Length > 0 && !force)
        {
            result.Skipped.Add(relativeName);
            return;
        }

        // Force: remove old .csproj files before writing fresh one
        var existed = existing.Length > 0;
        if (force)
            foreach (var old in existing)
                File.Delete(old);

        var content =
            "<Project Sdk=\"Godot.NET.Sdk/4.6.1\">\n" +
            "  <PropertyGroup>\n" +
            "    <TargetFramework>net8.0</TargetFramework>\n" +
            "    <EnableDynamicLoading>true</EnableDynamicLoading>\n" +
            "    <Nullable>enable</Nullable>\n" +
            "  </PropertyGroup>\n" +
            "</Project>\n";
        File.WriteAllText(Path.Combine(dir, $"{name}.csproj"), content);
        (existed ? result.Overwritten : result.Created).Add(relativeName);
    }

    private static void WriteSln(string dir, string name, bool force, ScaffoldResult result)
    {
        var existing = Directory.GetFiles(dir, "*.sln");
        var relativeName = $"{name}.sln";

        if (existing.Length > 0 && !force)
        {
            result.Skipped.Add(relativeName);
            return;
        }

        var existed = existing.Length > 0;
        if (force)
            foreach (var old in existing)
                File.Delete(old);

        var guid = Guid.NewGuid().ToString("D").ToUpperInvariant();
        var content =
            "Microsoft Visual Studio Solution File, Format Version 12.00\n" +
            $"Project(\"{{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}}\") = \"{name}\", \"{name}.csproj\", \"{{{guid}}}\"\n" +
            "EndProject\n" +
            "Global\n" +
            "\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n" +
            "\t\tDebug|Any CPU = Debug|Any CPU\n" +
            "\t\tRelease|Any CPU = Release|Any CPU\n" +
            "\tEndGlobalSection\n" +
            "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n" +
            $"\t\t{{{guid}}}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\n" +
            $"\t\t{{{guid}}}.Debug|Any CPU.Build.0 = Debug|Any CPU\n" +
            $"\t\t{{{guid}}}.Release|Any CPU.ActiveCfg = Release|Any CPU\n" +
            $"\t\t{{{guid}}}.Release|Any CPU.Build.0 = Release|Any CPU\n" +
            "\tEndGlobalSection\n" +
            "EndGlobal\n";
        File.WriteAllText(Path.Combine(dir, $"{name}.sln"), content);
        (existed ? result.Overwritten : result.Created).Add(relativeName);
    }

    private static void WriteMainScene(string dir, bool force, ScaffoldResult result)
    {
        var scenesDir = Path.Combine(dir, "scenes");
        Directory.CreateDirectory(scenesDir);
        var path = Path.Combine(scenesDir, "main.tscn");

        if (File.Exists(path) && !force)
        {
            result.Skipped.Add("scenes/main.tscn");
            return;
        }

        var existed = File.Exists(path);
        File.WriteAllText(path, MainSceneWriter.Write());
        (existed ? result.Overwritten : result.Created).Add("scenes/main.tscn");
    }

    private static string SanitiseProjectName(string dirName) =>
        string.IsNullOrWhiteSpace(dirName) ? "pmview-project" : dirName;
}

public class ScaffoldResult
{
    public List<string> Created { get; } = new();
    public List<string> Skipped { get; } = new();
    public List<string> Overwritten { get; } = new();
}
